<footer class="footer container-fluid">
    <div class="container-fluid">
        <div class="row">

        <div class="col-md-4">
            <div id="logo">
            <h4 class="main-font russo-">Movie Watchlist</h4>
            <p class="text-muted">Orgnaise your movies!</p>
            </div>
            
            <div id="contact">
                <h5 class="russo-one">Contact</h5>
                <dl>
                    <dt><i class="fas fa-envelope fa-2x dim-icon"></i></dt>
                    <dd>webmaster@example.com</dd>
                </dl>
            </div>

        </div>

        <div class="col-md-4">
            <div id="links">
                <h5 class="russo-one">Helpful Links</h5>
                <ul>
                    <li><a href="#" data-toggle='modal' data-target='#signupModalCenter'>Signup</a></li>
                    <li><a href="movielist.php">Movielist</a></li>
                </ul>
            </div>
        </div>

        <div class="col-md-4">
            <div id="search">
                <div class="form-inline">
                    <input class="form-control mr-sm-2" id="footer_search" name="search" placeholder="Search">
                    <input type="button" class="btn btn-outline-light my-2 my-sm-0" value="Search" id="button" onclick="search()">
                </div>



            </div>


        </div>

        </div>

        <hr class="bg-secondary">

        <div class="row">

            <div class="col-md-4 justify-content-center pt-4">
                <div id="socials">
                    <ul class="list-inline">
                        <li class="list-inline-item"><a href="http://instagram.com"><i class="fab fa-instagram fa-2x dim-icon"></i></a></li>
                        <li class="list-inline-item"><a href="http://facebook.com"><i class="fab fa-facebook-square fa-2x dim-icon"></i></a></li>
                        <li class="list-inline-item"><a href="http://github.com"><i class="fab fa-github fa-2x dim-icon"></i></a></li>
                    </ul>





                </div>
            </div>



            <div class="col-md-4 justify-content-end">
                <div class="copyright">
                    <small>Movielist Copyright &copy; <?php echo date("Y") ?> </small>
                </div>


                <div class="col-md-4 justify-content-start">
                    <div id="powered">
                        <ul class="list-inline">
                            <li class="list-inline-item"><a href="http://php.net"><i class="fab fa-php dim-icon"></i></a></li>
                            <li class="list-inline-item"><a href="http://jquery.com"><img src="img/jquery-icon.svg" alt="JQuery" class="dim-icon" height="25" width="50"></img></a></li>
                            <li class="list-inline-item"><a href="http://tmdb.org"><img src="img/tmdb_icon.svg" alt="TMDB" class="dim-icon"  height="25" width="50"></img></a></li>
                            <li class="list-inline-item"><a href="https://getbootstrap.com/"><i class="fab fa-bootstrap dim-icon"></i></a></li>
                        </ul>
                            
                    </div>

                </div>


            </div>
            
        </div>

    </div>
</footer>
</div>