<footer>
    <div class="h-auto container bg-dark pt-4 border-top border-secondary">
        <div class="row ml-4">

        <div class="col-sm-5">
            <div id="logo">
            <h4 class="main-font russo-">Movie Watchlist</h4>
            <p class="blockquote-footer font-weight-light text-light">Browse for movies & add them to your watchlist!</p>
            </div>
            
            <div id="contact" class="mt-5 text-light">
                <h5 class="russo-one">Contact</h5>
                <ul class="list-inline pt-2">
                    <li class="list-inline-item"><i class="fas fa-envelope fa-1x dim"></i></li>
                    <li class="list-inline-item">webmaster@example.com</li>
                </ul>
            </div>

        </div>

        <div class="col-sm-4 mx-auto">
            <div id="links">
                <h5 class="russo-one">Helpful Links</h5>
                <ul class="list-unstyled">
                    <li><a href="#" data-toggle='modal' data-target='#signupModalCenter'>Sign Up</a></li>
                    <li><a href="movielist.php">Movielist</a></li>
                </ul>
            </div>
        </div>

        <div class="col-auto ml-auto">
            <div id="search">
                <div class="input-group input-group-sm ">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fas fa-search fa-1x text-secondary"></i></span>
                      </div>
                    <input class="form-control" id="footer_search" name="search" placeholder="Search">
                </div>
            </div>
        </div>
        </div>

        <hr class="bg-secondary">

        <div class="row ml-4">

            <div class="col-sm-5 mr-auto">
                <div id="powered">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item"><a href="http://tmdb.org"><img src="img/tmdb_icon.svg" alt="TMDB" class="dim-icon"  height="25" width="50"></img></a></li>
                    </ul>
                        
                </div>

            </div>

            <div class="col-sm-4 mx-auto">
                <div id="socials">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item"><a href="http://instagram.com"><i class="fab fa-instagram text-light fa-2x dim-icon"></i></a></li>
                        <li class="list-inline-item"><a href="http://facebook.com"><i class="fab fa-facebook-square text-light fa-2x dim-icon"></i></a></li>
                        <li class="list-inline-item"><a href="http://github.com"><i class="fab fa-github fa-2x text-light dim-icon"></i></a></li>
                    </ul>
                </div>
            </div>



            <div class="col-sm-3 ml-auto">
                <div class="copyright">
                    <small class="text-light dim">Movielist Copyright &copy; <?php echo date("Y") ?> </small>
                </div>
            </div>
            
        </div>

    </div>
</footer>
</div>